
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: tinder_clone_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  app:
    build: .

    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8081:8081"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
